name: 'Samm YAML process Action'
description: 'Process YAML files and create markdown. Needs two associated volumes: one for Datafiles (yaml) and the other for output'
author: 'fzipi'
branding:
  icon: 'activity'
  color: 'blue'
inputs: 
  datafiles:
    description: 'Source directory with DataFiles'
    default: 'Datafiles'
  destination:
    description: 'Destination directory for processed markdown'
    default: 'output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-d ${{ inputs.datafiles }}"
    - "-o ${{ inputs.destination }}"
